#!/usr/bin/env bash
#===============================================================================
# payload
# by Caleb Foust (cfoust@sqweebloid.com)
#===============================================================================
# Builds Bash scripts with encrypted payloads. Viewer discretion is advised.
#===============================================================================
