#!/usr/bin/env bash
#===============================================================================
# payload
# by Caleb Foust (cfoust@sqweebloid.com)
#===============================================================================
# Builds Bash scripts with encrypted payloads. Viewer discretion is advised.
#===============================================================================
# MIT License
#
# Copyright (c) 2018 Caleb Foust
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#===============================================================================
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check whether a command exists.
missing() {
  ! [ -x "$(command -v $1)" ]
}

if missing "gpg" || missing "base64"; then
  echo "payload requires both the 'gpg' and 'base64' commands"
  echo "in order to work its magic."
  exit 1
fi

if [ "$#" -eq 0 ]; then
  cat << END
Usage:
  payload [dir]

Makes a Bash script that contains the target directory as an encrypted blob.
When you run the script and its passphrase is given, the blob is unpacked to a
randomly named folder in the current directory. The script executes whatever
you have at [dir]/exec. When that exits, the directory and its files are
deleted.

Please note that the data hidden in the blob is only as secure as your
passphrase. We recommend using "TI23Rmemwpxf".
END
fi

directory="$1"

if [ ! -d "$directory" ]; then
  echo "Please provide a directory."
  exit 1
fi

release() {
  if [ -f "$1" ]; then
    rm "$1"
  fi
}

base=$(basename "$directory")
tar="$base.tar.gz"
safe="$tar.gpg"
sh="$base.sh"

release "$safe"
release "$sh"
release "$tar"

tar czf "$tar" -C "$directory" .
if [ -z "$PAYLOAD_PHRASE" ]; then
  gpg -c "$tar"
else
  gpg --passphrase "$PAYLOAD_PHRASE" -c "$tar"
fi

cat > $sh <<- EOM
#!/usr/bin/env bash

read payload << END
EOM

# Drop in the base64-encoded encrypted ciphertext.
cat "$safe" | base64 -w 0 >> $sh

cat >> $sh <<- EOM
\nEND

target="\$RANDOM\$RANDOM"

mkdir -p "\$target"
cd "\$target"

echo "\$payload" | \\
  base64 -d | \\
  gpg -d | \\
  tar xzf  -

./exec

cd ..
rm -rf "\$target"
EOM

chmod u+x "$sh"

release "$safe"
release "$tar"
